apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: MODEL_MANAGER
  namespace: NAMESPACE
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - path: /api/v1/namespaces/(.*)/models
        pathType: Prefix
        backend:
          service:
            name: MODEL_MANAGER
            port:
              number: PORT
      - path: /api/v1/namespaces/(.*)/models/(.*)
        pathType: Prefix
        backend:
          service:
            name: MODEL_MANAGER
            port:
              number: PORTe
      - path: /api/v1/models*
        pathType: Prefix
        backend:
          service:
            name: MODEL_MANAGER
            port:
              number: PORT

